name: Test & Lint (Core)

on:
  push:
    paths:
      - '.github/workflows/test-and-lint-core.yml'
      - 'core/**.go'
      - 'core/go.mod'
  pull_request:
    paths:
      - '.github/workflows/test-and-lint-core.yml'
      - 'core/**.go'
      - 'core/go.mod'

jobs:
  core-test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - run: go get
      - run: go generate ./...

      - run: go test -v -race ./...
      - run: go vet ./...

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        if: github.event_name != 'pull_request'
        with:
          version: latest
          args: '--timeout 9999s'
