name: Lint

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/reviewdog.yml'
      - 'ui/**.{js,mjs,cjs,jsx,ts,mts,cts,tsx,vue}'
      - 'ui/package.json'
      - 'ui/pnpm-lock.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Check
        run: pnpm run check
